### ISSUE TITLE
Design Docs #1

### ISSUE THREAD

**Issue by rlim92** [AndyJia4700/IdeaBooster#1]
Hey Andy! Extremely well-detailed so far. Here are some tips below.

**MVP List**
- [x] for `project backer rewards` consider having simpler reward system for now (maybe just one reward type per project) and going back to flesh out more features after finishing the 4 core features. 

**Schema**
- [x] in `projects` table the `picture_url` and `video_url` columns can be taken out. You can (and should) use AWS to achieve photo/video hosting for the website.
- [x] `duration` should be changed to `end_date` in `projects` table if it refers to the actual end date (since it is a date type column).

**Comment by AndyJia4700** [comment]
Thank you so much for the feedback!
