### ISSUE TITLE
Design Docs Sample State Review

### ISSUE THREAD

**Issue by rlim92** [AndyJia4700/IdeaBooster#2]
Hey Andy! Everything looks good just one change:

**Sample State**
- [x] there are no commas separating the key-value pairs, make sure to include that for clarity. 
- [ ] instead of having a `backs` slice of state, have a `backer_ids` key in your `rewards` slice of state. This should return an array of ids of the backers associated with the reward (this can be grabbed through a getting method made by the association called `reward_instance.backer_ids`. With this array of references to user_ids, we can easily grab the backers through our `users` slice of state and not have repetitive information.
- [x] make sure the `ui` `errors` and `session` slice of state is at the same top level as `entities`. It should not be nested under `entities`.
- [ ] consider grabbing all `categories` and `locations` when users reach your site as it is likely these slices will be constantly pulled from by other slices. Depends on how many `categories` and `locations` you have and how often you believe they will be pulled from (dont have to add to sample state, just a thought for later).

**Comment by AndyJia4700** [comment]
for 2nd, added backer_ids into Rewards

is this ok? ****backer_ids: [[32,100], [5,100], [21,50] ....] (return an array of [backers.id, pledge amount]) } },

**Comment by rlim92** [comment]
Yes that makes sense.
